//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSventas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concepto
    {
        public long id { get; set; }
        public long id_venta_orden { get; set; }
        public int cantidad { get; set; }
        public decimal precioUnitario { get; set; }
        public decimal importe { get; set; }
        public int id_producto { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual VentaOrden VentaOrden { get; set; }
    }
}
