//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSventas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaOrden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VentaOrden()
        {
            this.Concepto = new HashSet<Concepto>();
        }
    
        public long id { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_cliente { get; set; }
        public int id_oficina { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Concepto> Concepto { get; set; }
        public virtual OficinaDeVenta OficinaDeVenta { get; set; }
    }
}
